### ISSUE TITLE
is $ref syntax supported

### ISSUE THREAD

**Issue by jahluwalia** [isa-group/oas-tools#63]
I currently have my swagger files divided across multiple files and use $ref. Is there a way to pass this 'chopped up' version of the swagger file to the initialize function?

Thanks,
Jas

**Comment by raffrearaUS** [comment]
oas-tools supports $ref wherever it is allowed according to the OpenAPI Specification (refer to [this page](https://swagger.io/docs/specification/using-ref/) for more information).
For example, you can have your method definitions in another file, so that your 'main' file is:
```yaml
...
paths:
  /pets:
    $ref: 'methods.yaml'
...
```
The file 'methods.yaml' must be accessible from a URL (for example, 'https://yourserver.com/methods.yaml').
Let me know if you have any more questions.
