### ISSUE TITLE
Combine middleware errors with custom handler

### ISSUE THREAD

**Issue by pnemi** [isa-group/oas-tools#84]
Hello,

is there a way how to combine pre-route middleware generated errors and my own validation errors thrown in controller/models?
Eg. returning to frontend one error object with "this parameter doesn't conform to OAS spec format" and "another param (ID for example) already exists in database" (which is not detectable by OAS-tools middleware)?

Thank for answer, you'll save my life.

**Comment by raffrearaUS** [comment]
Currently, oas-tools supports custom loggers through the `customLogger` configuration parameter. There, you can include your own Winston logger, so that it replaces the built-in one.
If this is not exactly what you need, please let me know what else we can do.

**Comment by robaca** [comment]
For me this sounds like we need the errors to be passed to `next()` instead of directly returning a response.
We have the same requirement. Fur custom error handling, it would also be important to identify validation errors. With swagger-tools, this was possible by checking for a `validationError` property.
